name: 'check for release'
description: 'Check if releases docker image'
outputs:
  skip:
    description: 'skip builder'
  docker_tag:
    description: "docker tag"
  git_hash:
    description: "gitea git hash"
runs:
  using: 'go'
  main: 'main.go'
