name: Docker build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0/2 * * *

jobs:
  check-release:
    runs-on: ubuntu-latest
    name: Check if image released
    outputs:
      LATEST_SKIP: ${{ steps.checker.outputs.LATEST_SKIP }}
      RELEASE_SKIP: ${{ steps.checker.outputs.RELEASE_SKIP }}
      # -----
      LATEST_DOCKER_TAG: ${{ steps.checker.outputs.LATEST_DOCKER_TAG }}
      RELEASE_DOCKER_TAG: ${{ steps.checker.outputs.RELEASE_DOCKER_TAG }}
      # -----
      LATEST_GIT_VERSION: ${{ steps.checker.outputs.LATEST_GIT_VERSION }}
      RELEASE_GIT_VERSION: ${{ steps.checker.outputs.RELEASE_GIT_VERSION }}
      # -----
      LATEST_GITEA_VERSION: ${{ steps.checker.outputs.LATEST_GITEA_VERSION }}
      RELEASE_GITEA_VERSION: ${{ steps.checker.outputs.RELEASE_GITEA_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: "./.github/checker/go.mod"
          cache: true

      - name: Release check
        id: checker
        uses: ./.github/checker
        env:
          GITEA_REPO: "https://github.com/go-gitea/gitea.git"
  
  main-build:
    if: needs.check-release.outputs.RELEASE_SKIP != '0' && needs.check-release.outputs.LATEST_SKIP == '0'
    needs: [ check-release ]
    name: Build main docker image
    uses: "./.github/workflows/call.yaml"
    secrets: inherit
    with:
      GITEA_TAG: ${{ needs.check-release.outputs.LATEST_GIT_VERSION }}
      DOCKER_TAG: ${{ needs.check-release.outputs.LATEST_DOCKER_TAG }}
      GITEA_REPO: "https://github.com/go-gitea/gitea.git"
      GITEA_VERSION: ${{ needs.check-release.outputs.LATEST_GITEA_VERSION }}

  release-build:
    if: needs.check-release.outputs.RELEASE_SKIP == '0'
    needs: [ check-release ]
    name: Build release docker image
    uses: "./.github/workflows/call.yaml"
    secrets: inherit
    with:
      GITEA_TAG: ${{ needs.check-release.outputs.RELEASE_GIT_VERSION }}
      DOCKER_TAG: ${{ needs.check-release.outputs.RELEASE_DOCKER_TAG }}
      GITEA_REPO: "https://github.com/go-gitea/gitea.git"
      GITEA_VERSION: ${{ needs.check-release.outputs.RELEASE_GITEA_VERSION }}
