name: Gitea
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0/6 * * *

concurrency:
  cancel-in-progress: true
  group: gitea-build

jobs:
  gitea:
    runs-on: ubuntu-latest
    name: Gitea build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: ./checker/go.mod
          cache-dependency-path: ./checker/go.sum
          cache: true

      - name: Build check
        working-directory: ./checker
        run: go build -v ./...

      - name: Check releases
        id: checker
        working-directory: ./checker
        run: go run .
        env:
          GITEA_REPO: "https://github.com/go-gitea/gitea.git"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: Sirherobrine23
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: Sirherobrine23
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3

      - name: Git build | Release
        uses: docker/build-push-action@v6
        if: ${{ steps.checker.outputs.release != '' }}
        id: release
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7
          target: gitea
          tags: |
            ghcr.io/sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.release).DOCKER_TAG}}
            sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.release).DOCKER_TAG}}
          build-args: |
            GITEA_TAG=${{fromJSON(steps.checker.outputs.release).GITEA_TAG}}
            GITEA_VERSION=${{fromJSON(steps.checker.outputs.release).GITEA_VERSION}}

      - name: Git build | Nightly
        uses: docker/build-push-action@v6
        if: ${{ steps.checker.outputs.nightly != '' }}
        id: nightly
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7
          target: gitea
          tags: |
            ghcr.io/sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.nightly).DOCKER_TAG}}
            sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.nightly).DOCKER_TAG}}
          build-args: |
            GITEA_TAG=${{fromJSON(steps.checker.outputs.nightly).GITEA_TAG}}
            GITEA_VERSION=${{fromJSON(steps.checker.outputs.nightly).GITEA_VERSION}}

      - name: Gogit build | Release
        uses: docker/build-push-action@v6
        if: ${{ steps.release.conclusion == 'success' }}
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7
          target: gitea
          tags: |
            ghcr.io/sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.release).DOCKER_TAG}}-gogit
            sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.release).DOCKER_TAG}}-gogit
          build-args: |
            GITEA_TAG=${{fromJSON(steps.checker.outputs.release).GITEA_TAG}}
            GITEA_VERSION=${{fromJSON(steps.checker.outputs.release).GITEA_VERSION}}
            GITEA_TAGS=gogit

      - name: Gogit build | Nightly
        uses: docker/build-push-action@v6
        if: ${{ steps.nightly.conclusion == 'success' }}
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7
          target: gitea
          tags: |
            ghcr.io/sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.nightly).DOCKER_TAG}}-gogit
            sirherobrine23/gitea:${{fromJSON(steps.checker.outputs.nightly).DOCKER_TAG}}-gogit
          build-args: |
            GITEA_TAG=${{fromJSON(steps.checker.outputs.nightly).GITEA_TAG}}
            GITEA_VERSION=${{fromJSON(steps.checker.outputs.nightly).GITEA_VERSION}}
            GITEA_TAGS=gogit